# Generated by Django 3.2.5 on 2021-08-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppReview', '0004_alter_userfollows_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-time_created'], 'verbose_name': 'Critique'},
        ),
    ]
