# Generated by Django 3.2.5 on 2021-08-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReview', '0005_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reply',
            field=models.BooleanField(default=False),
        ),
    ]
